main/forms.py
# -*- coding: utf-8 -*-
from flask_wtf import Form
from wtforms import SubmitField, StringField, PasswordField, SelectField, FieldList
from wtforms.validators import DataRequired, Length


class LibraryForm(Form):
    number = StringField(u'学号', validators=[DataRequired(), Length(1, 12)])
    passwd = PasswordField(u'密码', validators=[DataRequired()])
    submit = SubmitField(u'登陆')

class LibraryHistForm(Form):
    number = StringField(u'学号', validators=[DataRequired(), Length(1, 12)])
    passwd = PasswordField(u'密码', validators=[DataRequired()])
    submit = SubmitField(u'登陆')

class LibraryBuilding(Form):
    password = PasswordField(u'密码', validators=[DataRequired()])
    submit = SubmitField(u'登陆')



class JwcForm(Form):
    number = StringField(u'学号', validators=[DataRequired(), Length(1, 12)])
    passwd = PasswordField(u'密码', validators=[DataRequired()])
    check_code = StringField(u'验证码', validators=[DataRequired()])
    submit1 = SubmitField(u'登陆')


class ScoreForm(Form):
    post_xuehao = StringField(u'学号', validators=[DataRequired(), Length(1, 12)])
    submit = SubmitField(u'查询')


class CetForm(Form):
    name = StringField(u'姓名', validators=[DataRequired(), Length(1, 12)])
    number = StringField(u'准考证号', validators=[DataRequired(), Length(1, 16)])
    submit = SubmitField(u'查询')

app/main/__init__.py
from flask import Blueprint

main = Blueprint('main', __name__)

from . import views

app/main/views/__init__.py
from . import index
from . import library
from . import jwch
from . import zhengfang
from . import zhengfang_class
from . import part_time_job

app/main/views/index.py
# coding=utf-8
from flask import render_template
from datetime import datetime
from .. import main

# 主页内容
@main.route('/')
@main.route('/index')
@main.route('/home')
def index():
    """Renders the home page."""
    return render_template(
        'index.html',
        title=u'主页',
        year=datetime.now().year,
    )


@main.route('/contact')
def contact():
    """Renders the contact page."""
    return render_template(
        'contact.html',
        title=u'联系我们',
        year=datetime.now().year,
        message1=u'山东理工大学Linux用户组',
        message2=u'山东理工大学报',
        connection=u'如果您发现bug请联系：'
    )


@main.route('/about')
def about():
    """Renders the about page."""
    return render_template(
        'about.html',
        title=u'关于本站',
        year=datetime.now().year,
        message=u'山东理工大学信息一站式查询系统'
    )


@main.route('/notice')
def notice():
    return render_template(
        'notice.html',
        title=u'通知'
    )

app/main/views/jwch.py
# coding=utf-8
from flask import render_template
from flask import request
from flask import session
from bs4 import BeautifulSoup
from .. import main
import copy
import requests

# 教务综合成绩查询页面内容
URL = 'http://210.44.176.116/cjcx/zcjcx_list.php'


def get_grade_list(studentno):
    data = {'post_xuehao': studentno}
    res = requests.post(URL, data=data)
    soup = BeautifulSoup(res.text)

    # 获得学生信息
    try:
        info = {
            'no': studentno,
            'name': soup.body.table.find_all('table')[0].find_all('tr')[1].find_all('td')[1].text,
            'class': soup.body.table.find_all('table')[0].find_all('tr')[1].find_all('td')[6].text
        }
    except:
        return None

    # 获得学生成绩单
    gradelist = []
    len = 0
    for grade in soup.body.table.find_all('table')[2].find_all('tr'):
        if len == 0:
            len += 1
            continue

        # 跳过双专业
        way = grade.find_all('td')[8].text.strip()
        if way.isalpha():
            continue

        tmp = {
            'id': grade.find_all('td')[0].text.strip(),
            'schoolyear': grade.find_all('td')[1].text.strip(),
            'semester': grade.find_all('td')[2].text.strip(),
            'class': grade.find_all('td')[3].text.strip(),
            'name': grade.find_all('td')[5].text.strip(),
            'point': grade.find_all('td')[7].text.strip(),
            'grade': grade.find_all('td')[9].text.strip()
        }

        update = grade.find_all('td')[10].text.strip()
        if update is not None and update.isdigit():
            tmp['grade'] = update

        gradelist.append(tmp)

    return {
        'info': info,
        'gradelist': gradelist
    }


def get_student(studentno):
    gradelist = get_grade_list(studentno)
    if gradelist is None:
        return None
    pointinfo = computer(gradelist)
    return {
        'gradelist': gradelist,
        'pointinfo': pointinfo
    }


def computer(gradelist):
    sumgrade = 0.0
    sumpoint = 0.0
    pointinfo = {}

    for g in gradelist['gradelist']:
        if g['class'] != u'公选课':
            gradetmp = __score2number(g['grade'])
            if gradetmp < 60:
                gradetmp = 0.0

            pointtmp = float(g['point'])
            sumgrade += gradetmp * pointtmp
            if g['name'] not in pointinfo:
                sumpoint += pointtmp
                pointinfo[g['name']] = gradetmp
            else:
                if gradetmp > pointinfo[g['name']]:
                    sumgrade -= pointinfo[g['name']] * pointtmp
                    pointinfo[g['name']] = gradetmp

    pointinfo['sumgrade'] = sumgrade
    pointinfo['sumpoint'] = sumpoint
    pointinfo['point'] = sumgrade / sumpoint

    return pointinfo


def __score2number(text):
    '''将二级和五级成绩转换成数字成绩,或者将成绩转换成浮点型'''
    sc_dict = {
        u'合格': 70,
        u'不合格': 0,
        u'优秀': 95,
        u'良好': 84,
        u'中等': 73,
        u'及格': 62,
        u'不及格': 0,
        u'缺考': 0,
        u'禁考': 0,
        u'退学': 0,
        u'缓考（时': 0,
        u'缓考': 0,
        u'休学': 0,
        u'未选': 0,
        u'作弊': 0,
        u'取消': 0,
        u'免修': 60,
        u'优': 95,
        u'良': 84,
        u'中': 73,
        u'-': 0,
        u'': 0
    }
    try:
        num = sc_dict[text]
        return num
    except:
        try:
            num = float(text)
            return num
        except:
            return 0


@main.route('/find')
def find():
    return render_template('main/find.html')


@main.route('/list', methods=['POST'])
def ans():
    if request.method == 'POST':
        student = request.form['number']

        if student.isdigit():
            studentinfo = get_student(student)
            if studentinfo is not None:
                # 加入session
                session['user'] = studentinfo['gradelist']
                return render_template(
                    'main/ans.html',
                    info=studentinfo['gradelist'],
                    point=studentinfo['pointinfo']
                )

    return render_template('main/find.html')


@main.route('/update', methods=['POST'])
def update():
    if request.method == 'POST':
        # student = request.form['no']
        gradelist = copy.deepcopy(session['user'])
        len = 1
        for grade in gradelist['gradelist']:
            grade['grade'] = request.form['c' + str(len)]
            len += 1

        gradelist = computer(gradelist)
        return render_template(
            'main/ans.html',
            info=session['user'],
            point=gradelist
        )

    return render_template('main/find.html')

app/main/views/library.py
# coding=utf-8
from flask import render_template
from flask import flash
from flask import request
from requests import Session
from bs4 import BeautifulSoup
from ..forms import LibraryForm
from .. import main


# 图书借阅页面
@main.route('/library', methods=['GET', 'POST'])
def library():
    form = LibraryForm()
    number = form.number.data
    passwd = form.passwd.data
    if request.method == 'GET':
        return render_template('main/library_login.html', form=form)
    elif request.method == 'POST':
        post_data = {
            "number": number,
            "passwd": passwd,
            "returnUrl": "",
            "select": "cert_no"
        }
        url_Seeeion = Session()
        temp = url_Seeeion.post("http://222.206.65.12/reader/redr_verify.php", post_data)
        book_list_url = url_Seeeion.get("http://222.206.65.12/reader/book_lst.php")
        if book_list_url.url == 'http://222.206.65.12/reader/book_lst.php':  # url相同意味着登陆成功
            soup = BeautifulSoup(book_list_url.text, 'html5lib')
            html_td = soup.find_all('td', bgcolor="#FFFFFF")
            try:
                j = 0
                books = []
                abook = {}
                for i in range(0, len(html_td) / 8):
                    abook['number'] = html_td[j].get_text().strip()
                    abook['name'] = html_td[j + 1].get_text().strip()
                    abook['author'] = html_td[j + 2].get_text().strip()
                    abook['borrowing_date'] = html_td[j + 3].get_text().strip()
                    abook['return_date'] = html_td[j + 4].get_text().strip()
                    abook['continue'] = u'续借'
                    j += 8
                    books.append(abook)
                    abook = {}
                return render_template('main/library.html', books=books, number=number, passwd=passwd)
            except:
                return render_template('main/library_no_books.html', number=number, passwd=passwd)
        else:  # 登录失败返回对应提示的字符串
            flash(u'帐号或密码错误')
            return render_template('main/library_login.html', form=form)
    else:
        return u'对不起，您的请求非法'


@main.route('/library_history', methods=['GET', 'POST'])
def book_history():
    if request.method == 'POST':
        number = request.form['number']
        passwd = request.form['pass']
        login_url = 'http://222.206.65.12/reader/redr_verify.php'
        book_hist_url = 'http://222.206.65.12/reader/book_hist.php'
        data = {
            'number': number,
            'passwd': passwd,
            'returnUrl': '',
            'select': 'cert_no'
        }
        url_session = Session()

        temp = url_session.post(login_url, data=data)
        hist_data = {
            'para_string': 'all'
        }
        book_hist = url_session.post(book_hist_url, data=hist_data)
        page_content = book_hist.content
        soup = BeautifulSoup(page_content, 'html5lib')
        html_td = soup.find_all('td', bgcolor="#FFFFFF")
        j = 0
        books = []
        abook = {}
        # print html_td[13].get_text().strip()
        for i in range(0, len(html_td) / 7):
            abook['xuhao'] = html_td[j].get_text().strip()
            abook['number'] = html_td[j + 1].get_text().strip()
            abook['name'] = html_td[j + 2].get_text().strip()
            abook['author'] = html_td[j + 3].get_text().strip()
            abook['borrowing_date'] = html_td[j + 4].get_text().strip()
            abook['return_date'] = html_td[j + 5].get_text().strip()
            abook['position'] = html_td[j + 6].get_text().strip()

            j += 7
            books.append(abook)
            abook = {}

        return render_template('main/book_history.html', books=books)

app/main/views/part_time_job.py
from app.main import main
from app import db
from app.models import Message
from flask import render_template, request, redirect, url_for, flash
from datetime import datetime


@main.route('/part-time-job')
def part_time_job():
    all_message = Message.query.order_by(Message.id)
    return render_template(
        'main/part_time_job.html',
        all_message=all_message,
        title=u'兼职平台',
        year=datetime.now().year,
    )


@main.route('/part-time-job/manage', methods=['GET', 'POST'])
def part_time_job_manage():
    if request.method == 'GET':
        return render_template(
            'main/part_time_job_manage.html',
            title=u'兼职平台信息管理',
            job_time=datetime.now(),
            year=datetime.now().year,
        )
    else:
        print(request.form)
        job_time = request.form['job_time']
        print(job_time)
        job_title = request.form['job_title']
        job_content = request.form['job_content']
        job_contact = request.form['job_contact']
        a_message = Message(title=job_title, date=job_time, content=job_content, contact=job_contact)
        db.session.add(a_message)
        db.session.commit()
        flash(u"上一条兼职信息已经发布，如需操作请继续")
        return redirect(url_for("main.part_time_job_manage"))

app/wechat/views/library.py
# coding=utf-8
from flask import render_template
from flask import flash
from flask import request
from requests import Session
from app.models import User
from bs4 import BeautifulSoup
from ..forms import LibraryForm
from .. import wechat


# 图书借阅页面
@wechat.route('/library', methods=['GET', 'POST'])
def library():
    form = LibraryForm()
    if request.method == 'GET':
        wechat_id = request.args.get('wechat_id')
        account = User.query.filter_by(wechat_id=wechat_id).first()
        return render_template(
            'wechat/library_login.html',
            form=form,
            number=account.stu_number,
            passwd=account.library_password,
            wechat_id=wechat_id
        )
    elif request.method == 'POST':
        number = form.number.data
        passwd = form.passwd.data
        post_data = {
            "number": number,
            "passwd": passwd,
            "returnUrl": "",
            "select": "cert_no"
        }
        url_Seeeion = Session()
        temp = url_Seeeion.post("http://222.206.65.12/reader/redr_verify.php", post_data)
        book_list_url = url_Seeeion.get("http://222.206.65.12/reader/book_lst.php")
        if book_list_url.url == 'http://222.206.65.12/reader/book_lst.php':  # url相同意味着登陆成功
            soup = BeautifulSoup(book_list_url.text, 'html5lib')
            html_td = soup.find_all('td', bgcolor="#FFFFFF")
            try:
                j = 0
                books = []
                abook = {}
                # print html_td[5].get_text().strip()
                for i in range(0, len(html_td) / 8):
                    abook['number'] = html_td[j].get_text().strip()
                    abook['name'] = html_td[j + 1].get_text().strip()
                    abook['author'] = html_td[j + 2].get_text().strip()
                    abook['borrowing_date'] = html_td[j + 3].get_text().strip()
                    abook['return_date'] = html_td[j + 4].get_text().strip()
                    abook['continue'] = u'续借'
                    j += 8
                    books.append(abook)
                    abook = {}
                return render_template('main/library.html', books=books, number=number, passwd=passwd)
            except:
                return render_template('main/library_no_books.html', number=number, passwd=passwd)
        else:  # 登录失败返回对应提示的字符串
            flash(u'帐号或密码错误')
            return render_template('main/library_login.html', form=form)
    else:
        return u'对不起，您的请求非法'

app/templates/main/ans.html
<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="不要跟我学扳着手指考试，Just for fun。">
    <meta name="author" content="Hypo">

    <title>山东理工大学绩点查询估算</title>

    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/bootstrap.min.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/home.css') }}">
</head>

<body>

<div class="container">
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a href="/" class="navbar-brand">New Gotit</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a href="{{ url_for('main.index') }}">主页</a></li>
                    <li><a href="{{ url_for('main.notice') }}">通告</a></li>
                    <li><a href="{{ url_for('main.about') }}">关于</a></li>
                    <li><a href="{{ url_for('main.contact') }}">联系我们</a></li>
                </ul>
            </div>
        </div>
    </div>
<h1>&nbsp;</h1>

    <div class="jumbotron">
        <label>{{ info['info']['number'] }} | {{ info['info']['name'] }} | {{ info['info']['class'] }}</label>
        <h2>目前绩点：<b>{{ point['point'] }}</b></h2>
        <p>已修总绩点: {{ point['sumgrade'] }} | 总学分: {{ point['sumpoint'] }}</p>
    </div>

    <div class="row">
        <div class="col-lg-12">
            <form id="update" method="POST" action="{{ url_for('main.update') }}">
                <input type="hidden" name="no" value="{{ info['info']['number'] }}"/>
                <table class="table table-striped table-bordered table-hover">
                    <thead>
                    <tr>
                        <th>#</th>
                        <th>学年</th>
                        <th>学期</th>
                        <th>类别</th>
                        <th>课程名称</th>
                        <th>学分</th>
                        <th>原成绩</th>
                        <th>预计重修成绩</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for grade in info['gradelist'] %}
                        {% if grade['class'] == "公选课" %}
                            <tr class="info">
                                {% elif point[grade['name']] < 60 %}
                            <tr class="danger">
                                {% elif point[grade['name']] < 70 %}
                            <tr class="warning">
                                {% else %}
                            <tr>
                        {% endif %}
                    <th scope="row">{{ grade['id'] }}</th>
                    <td>{{ grade['schoolyear'] }}</td>
                    <td>{{ grade['semester'] }}</td>
                    <td>{{ grade['class'] }}</td>
                    <td>{{ grade['name'] }}</td>
                    <td>{{ grade['point'] }}</td>
                    <td>{{ grade['grade'] }}</td>
                    <td><input type="text" class="form-control" name="c{{ grade['id'] }}"
                               value="{{ point[grade['name']] }}" placeholder="{{ grade['grade'] }}"></td>
                    </tr>
                    {% endfor %}
                    </tbody>
                </table>
                <div class="alert alert-success" role="alert">
                    <ul>
                        <li><span class="label label-info">公选课</span>已经用蓝色标注，不计入绩点计算，所以也不用尝试修改成绩</li>
                        <li><span class="label label-warning">低于70分的课程</span>用黄色标注，如果绩点不够，可以考虑重修</li>
                        <li><span class="label label-danger">没有通过的课程</span>用红色标注，如果认为自己补考能过，可以手动修改并重新计算</li>
                        <li>建议从下到上修改成绩进行重新计算，因为如果重修，将按照考试时间最近的成绩为计算依据</li>
                        <li>本程序忽略了公选课的学分统计和第二专业的绩点计算，这两个功能山理麒麟做的不错 :)</li>
                        <li>本程序只是经过简单测试，如果遇到问题欢迎反馈：i@ihypo.net</li>
                        <li>如果程序崩溃，一般重启浏览器就好了 :)</li>
                    </ul>
                </div>
                <button type="submit" class="btn btn-info btn-sm">重新计算</button>
            </form>
        </div>
    </div>

    <footer class="footer">
        <p>&copy; OpenSDUT 2016 此模块由<a href="http://www.ihypo.net">hypo</a>提供技术支持 </p>
    </footer>

</div> <!-- /container -->
<script>
    var _hmt = _hmt || [];
    (function () {
        var hm = document.createElement("script");
        hm.src = "//hm.baidu.com/hm.js?027c62c82667fbc59c9f87a7a28e2da3";
        var s = document.getElementsByTagName("script")[0];
        s.parentNode.insertBefore(hm, s);
    })();
</script>
</body>
</html>

app/templates/main/book_history.html
{% extends "base.html" %}

{% block page_content %}
    <h3>图书馆历史借阅情况如下：</h3>

    <table class="table table-bordered">
        <tr>
            <td class="success">序号</td>
            <td class="success">条码号</td>
            <td class="success">题名</td>
            <td class="success">责任者</td>
            <td class="success">借阅日期</td>
            <td class="success">应还日期</td>

        </tr>
        {% for book in books %}
            <tr>
                <td class="info">{{ book['xuhao'] }}</td>
                <td class="info">{{ book['number'] }}</td>
                <td class="info">{{ book['name'] }}</td>
                <td class="info">{{ book['author'] }}</td>
                <td class="info">{{ book['borrowing_date'] }}</td>
                <td class="info">{{ book['return_date'] }}</td>

            </tr>
        {% endfor %}

    </table>
{% endblock %}

app/templates/main/class.html
{% extends "base.html" %}

{% block page_content %}
    <h3>您的个人信息如下：</h3>

    <table class="table table-bordered">
        <tr>
            <td class="success">学号</td>
            <td class="success">姓名</td>
            <td class="success">学院</td>
            <td class="success">专业</td>
            <td class="success">班级</td>
        </tr>
        <tr>
            <td class="info">{{ return_info[0][0] }}</td>
            <td class="info">{{ return_info[0][1] }}</td>
            <td class="info">{{ return_info[0][2] }}</td>
            <td class="info">{{ return_info[0][3] }}</td>
            <td class="info">{{ return_info[0][4] }}</td>
        </tr>
    </table>
    <h3>此学期课表如下：</h3>
    <table class="table table-bordered">

        <tr>
            <td class="success">#</td>
            <td class="success">星期一</td>
            <td class="success">星期二</td>
            <td class="success">星期三</td>
            <td class="success">星期四</td>
            <td class="success">星期五</td>
            <td class="success">星期六</td>
            <td class="success">星期日</td>
        </tr>

        <tr>
            <td class="info"> 第一二节</td>
            <td class="info">{{ return_info[1][0][0] }}</td>
            <td class="info">{{ return_info[1][0][1] }}</td>
            <td class="info">{{ return_info[1][0][2] }}</td>
            <td class="info">{{ return_info[1][0][3] }}</td>
            <td class="info">{{ return_info[1][0][4] }}</td>
            <td class="info">{{ return_info[1][0][5] }}</td>
            <td class="info">{{ return_info[1][0][0] }}</td>

        </tr>
        <tr>
            <td class="info"> 第三四节</td>
            <td class="info">{{ return_info[1][1][0] }}</td>
            <td class="info">{{ return_info[1][1][1] }}</td>
            <td class="info">{{ return_info[1][1][2] }}</td>
            <td class="info">{{ return_info[1][1][3] }}</td>
            <td class="info">{{ return_info[1][1][4] }}</td>
            <td class="info">{{ return_info[1][1][5] }}</td>
            <td class="info">{{ return_info[1][1][0] }}</td>

        </tr>
        <tr>
            <td class="info"> 第五六节</td>
            <td class="info">{{ return_info[1][2][0] }}</td>
            <td class="info">{{ return_info[1][2][1] }}</td>
            <td class="info">{{ return_info[1][2][2] }}</td>
            <td class="info">{{ return_info[1][2][3] }}</td>
            <td class="info">{{ return_info[1][2][4] }}</td>
            <td class="info">{{ return_info[1][2][5] }}</td>
            <td class="info">{{ return_info[1][2][0] }}</td>

        </tr>
        <tr>
            <td class="info"> 第七八节</td>
            <td class="info">{{ return_info[1][3][0] }}</td>
            <td class="info">{{ return_info[1][3][1] }}</td>
            <td class="info">{{ return_info[1][3][2] }}</td>
            <td class="info">{{ return_info[1][3][3] }}</td>
            <td class="info">{{ return_info[1][3][4] }}</td>
            <td class="info">{{ return_info[1][3][5] }}</td>
            <td class="info">{{ return_info[1][3][0] }}</td>

        </tr>
        <tr>
            <td class="info"> 第九十节</td>
            <td class="info">{{ return_info[1][4][0] }}</td>
            <td class="info">{{ return_info[1][4][1] }}</td>
            <td class="info">{{ return_info[1][4][2] }}</td>
            <td class="info">{{ return_info[1][4][3] }}</td>
            <td class="info">{{ return_info[1][4][4] }}</td>
            <td class="info">{{ return_info[1][4][5] }}</td>
            <td class="info">{{ return_info[1][4][0] }}</td>

        </tr>



    </table>
{% endblock %}

app/templates/main/find.html
<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="不要跟我学扳着手指考试，Just for fun。">
    <meta name="author" content="Hypo">

    <title>山东理工大学绩点查询估算</title>

    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/bootstrap.min.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/home.css') }}">
</head>

<body>

<div class="container">
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a href="/" class="navbar-brand">New Gotit</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a href="{{ url_for('main.index') }}">主页</a></li>
                    <li><a href="{{ url_for('main.notice') }}">通告</a></li>
                    <li><a href="{{ url_for('main.about') }}">关于</a></li>
                    <li><a href="{{ url_for('main.contact') }}">联系我们</a></li>
                </ul>
            </div>
        </div>
    </div>
    <h1>&nbsp;</h1>
    <div class="jumbotron">
        <h2>绩点计算查询</h2>
        <form action="{{ url_for('main.ans') }}" method="POST">
            <div class="form-group">
                <label>请输入学号</label>
                <input type="text" class="form-control" name="number" placeholder="学号">
            </div>
            <button type="submit" class="btn btn-success">开始计算</button>
            <a class="btn btn-link" target="_blank" href="http://210.44.176.116/cjcx/main.html">计算方法</a>
        </form>
    </div>

    <footer class="footer">
        <p>&copy; OpenSDUT 2016 此模块由<a href="http://www.ihypo.net">hypo</a>提供技术支持 </p>
    </footer>

</div> <!-- /container -->
<script>
    var _hmt = _hmt || [];
    (function () {
        var hm = document.createElement("script");
        hm.src = "//hm.baidu.com/hm.js?027c62c82667fbc59c9f87a7a28e2da3";
        var s = document.getElementsByTagName("script")[0];
        s.parentNode.insertBefore(hm, s);
    })();
</script>
</body>
</html>

app/templates/main/library.html
{% extends "base.html" %}

{% block page_content %}
    <h3>图书馆借阅情况如下：</h3>
    <form action="{{ url_for('main.book_history') }}" method="post">
        <input type="hidden" value="{{ number }}" name="number"/>
        <input type="hidden" value="{{ passwd }}" name="pass">
        <h3><input class="btn-info" type="submit" value="点击查看历史借阅情况"></h3>
    </form>

    <table class="table table-bordered">
        <tr>
            <td class="success">条码号</td>
            <td class="success">题名</td>
            <td class="success">责任者</td>
            <td class="success">借阅日期</td>
            <td class="success">应还日期</td>
        </tr>
        {% for book in books %}
            <tr>
                <td class="info">{{ book['number'] }}</td>
                <td class="info">{{ book['name'] }}</td>
                <td class="info">{{ book['author'] }}</td>
                <td class="info">{{ book['borrowing_date'] }}</td>
                <td class="info">{{ book['return_date'] }}</td>
            </tr>
        {% endfor %}

    </table>
{% endblock %}

app/templates/main/library_login.html
{% extends "base.html" %}

{% block page_content %}


    <form method="post" class="form-signin">
        <h2 class="form-signin-heading">图书馆借阅查询</h2>
        {{ form.hidden_tag() }}
        {{ form.number.label }} {{ form.number( class="form-control",placeholder="学号") }}
        <br/>
        {{ form.passwd.label }} {{ form.passwd(class="form-control",placeholder="密码") }}
        <br/>
        {{ form.submit(class="btn btn-lg btn-primary btn-block") }}

    </form>




{% endblock %}

app/templates/main/library_no_books.html
{% extends "base.html" %}

{% block page_content %}
    <h3>图书馆借阅情况如下：</h3>
    <h4>哎呀，您好像一本书也没借</h4>
    <form action="{{ url_for('main.book_history') }}" method="post">
        <input type="hidden" value="{{ number }}" name="number"/>
        <input type="hidden" value="{{ passwd }}" name="pass">
        <input class="btn bnt-default" type="submit" value="点击查看借阅历史记录">
    </form>
{% endblock %}